### ISSUE TITLE
Encountered an Error

### ISSUE THREAD

**Issue by 123-afri** [youngskkim/CRN#1]
am currently pursuing my Master's in Artificial Intelligence, and I've utilized your research paper as a fundamental reference for my project implementation. While working on the code, I encountered an error due to the absence of nuscenes_infos_train.pkl and nuscenes_infos_val.pkl files in the directory specified by the code. These files seem crucial for the code's functionality. Could you provide more details or guidance on where to find or generate these files? Your prompt response would greatly assist me as I'm dedicating significant effort to this project and seeking to resolve this issue urgently. Thank you.

**Comment by stduent-vehicle** [comment]
> am currently pursuing my Master's in Artificial Intelligence, and I've utilized your research paper as a fundamental reference for my project implementation. While working on the code, I encountered an error due to the absence of nuscenes_infos_train.pkl and nuscenes_infos_val.pkl files in the directory specified by the code. These files seem crucial for the code's functionality. Could you provide more details or guidance on where to find or generate these files? Your prompt response would greatly assist me as I'm dedicating significant effort to this project and seeking to resolve this issue urgently. Thank you.

Have you tried: python scripts/gen_info.py

**Comment by youngskkim** [comment]
As @Gang-Chen-China suggested, you can generate `nuscenes_infos_[train,val].pkl` files using `python scripts/gen_info.py`.

**Comment by 123-afri** [comment]
Dear youngskkim and Gang-Chen-China,I have been working on camera and radar fusion for over two and a half years, encountering various issues and errors while implementing the project. Despite attempting multiple repositories from GitHub, I consistently faced errors in each one. I've also revisited your repository several times, but encountered errors I also tried to  run the python scripts/gen_info.py file as instructed. but again I obtained error.Considering the challenges I've faced, I kindly request your assistance in re-implementing this project. I've already downloaded the dataset from NuScenes and obtained the code repository. I use an NVIDIA RTX A2000 GPU, and I'm willing to provide you with my GPU credentials so you can access it remotely via AnyDesk software. This would allow you to reproduce the project on my system, a process that may take around two to three hours.As a master's student, I've chosen your research paper as a cornerstone for my thesis. I've invested a significant amount of time and effort into this project, and your guidance would immensely help me in continuing my work. I would be immensely grateful for your support in this matter.Thank you for considering my request. Your assistance would be invaluable to me.Sincerely,
Please reply me within 15 hours as It will be highly helpful to me.
Muhammad Haroon Afridi
Graduate Research Assistant

**Comment by 123-afri** [comment]
Dear youngskkim and Gang-Chen-China,I have been working on camera and radar fusion for over two and a half years, encountering various issues and errors while implementing the project. Despite attempting multiple repositories from GitHub, I consistently faced errors in each one. I've also revisited your repository several times, but encountered errors I also tried to run the python scripts/gen_info.py file as instructed. but again I obtained error.Considering the challenges I've faced, I kindly request your assistance in re-implementing this project. I've already downloaded the dataset from NuScenes and obtained the code repository. I use an NVIDIA RTX A2000 GPU, and I'm willing to provide you with my GPU credentials so you can access it remotely via AnyDesk software. This would allow you to reproduce the project on my system, a process that may take around two to three hours.As a master's student, I've chosen your research paper as a cornerstone for my thesis. I've invested a significant amount of time and effort into this project, and your guidance would immensely help me in continuing my work. I would be immensely grateful for your support in this matter.Thank you for considering my request. Your assistance would be invaluable to me.Sincerely,
Please reply me within 15 hours as It will be highly helpful to me.
Graduate Research Assistant

**Comment by stduent-vehicle** [comment]
Can you provide more details about your problems?

**Comment by 123-afri** [comment]
Dear sir you did not specify  python file about the training and evaluation as in the following command it is not specified.
For training:
python [EXP_PATH] --amp_backend native -b 4 --gpus 4
For evaluation:
 python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 4 --gpus 4
 Could you clarify above two commands that what should be provided in the place of EXP_PATH?
 Please brief me about this issue.
 Please reply me as soon as possible.
 Thankyou.

**Comment by 123-afri** [comment]
Could you please tell me about the dataset's size used in the project? Additionally, could you provide its data path, structure, and include a screenshot for reference? I'd appreciate a comprehensive explanation regarding the dataset's specifics.

**Comment by stduent-vehicle** [comment]
Can you provide your screenshot? because it's not difficult to use this repo.

> Dear sir you did not specify python file about the training and evaluation as in the following command it is not specified. For training: python [EXP_PATH] --amp_backend native -b 4 --gpus 4 For evaluation: python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 4 --gpus 4 Could you clarify above two commands that what should be provided in the place of EXP_PATH? Please brief me about this issue. Please reply me as soon as possible. Thankyou.

If you want to train the model, you can use this command:  python  ./exps/det
/CRN_r50_256x704_128x128_4key.py --amp_backend native -b 4 --gpus 4

**Comment by 123-afri** [comment]
When I run the command in the above comment for training. I found this error which are given in the pic. 
![IMG_20240102_143403](https://github.com/youngskkim/CRN/assets/101881801/06259bb1-00ff-4894-80f9-11f007248b30)

**Comment by 123-afri** [comment]
Despite I have images in the directory Samples. 
![Uploading 17041884685654844538423776920269.jpg…]()

**Comment by stduent-vehicle** [comment]
Do you succeed generate  nuscenes_infos_train.pkl in the directory /data/nuScenes?

**Comment by stduent-vehicle** [comment]
> When I run the command in the above comment for training. I found this error which are given in the pic. ![IMG_20240102_143403](https://private-user-images.githubusercontent.com/101881801/293663109-06259bb1-00ff-4894-80f9-11f007248b30.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODg5MTEsIm5iZiI6MTcwNDE4ODYxMSwicGF0aCI6Ii8xMDE4ODE4MDEvMjkzNjYzMTA5LTA2MjU5YmIxLTAwZmYtNDg5NC04MGY5LTExZjAwNzI0OGIzMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTQzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDZkMmFjMjBkYjk0Y2NlZDIzZjgyZGFlMDY4N2JkMGE2YWRhNTE3ZjE0MzY0YTQ0NTAzZjA3ZmY2MjY5MWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zY2g4iXX6lRLhLDao0PKjvmyxxpmREn6N9PEKbQ19G4)

The folder structure will be as follows:
CRN
├── data
│   ├── nuScenes
│   │   ├── nuscenes_infos_train.pkl
│   │   ├── nuscenes_infos_val.pkl
│   │   ├── maps
│   │   ├── samples
│   │   ├── sweeps
|   |   ├── depth_gt
|   |   ├── radar_bev_filter  # temporary folder, safe to delete
|   |   ├── radar_pv_filter
|   |   ├── v1.0-trainval

**Comment by 123-afri** [comment]
Despite I have images in the Sample directory
![IMG_20240102_144320](https://github.com/youngskkim/CRN/assets/101881801/71978846-4074-4129-abd3-1e37a906fd13)

**Comment by 123-afri** [comment]
> Do you succeed generate nuscenes_infos_train.pkl in the directory /data/nuScenes?

Yes I succeed. As you can see it in the pic. 
![Uploading IMG_20240102_144658.jpg…]()

**Comment by 123-afri** [comment]
> Do you succeed generate nuscenes_infos_train.pkl in the directory /data/nuScenes?

Yes I succeed. You can see it in the attach pic. 
![IMG_20240102_144658](https://github.com/youngskkim/CRN/assets/101881801/144b4049-9460-422b-b059-8d1694b40000)

**Comment by 123-afri** [comment]
I am waiting for your response dear brother. As I am obtaining the same error again and again which i shown you in the above attached picture. Despite the availability of **Samples**  directory in which contained camera images.
So plz guide me regarding this.
So please access my GPU using following instructions:
1: download anydesk software which is about 5 to 6MB.
2:give my IP address which is 1780133641
3: Give anydesk password which is "giki123@"
4:Login username "Haroon" giving password which is "Haroon123@"
I made CRN  directory in the home in which have code data.
So plz do it for me as I will be highly thankful to you.
I tried very hard as I shown you my working but I did not succed in implementing it.
I have very short time in my MS.

**Comment by 123-afri** [comment]
Aoa dear sir please reply me.
