### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by Deltaidiots** [youngskkim/CRN#10]
Can you also provide the visualization script as shown in video please?

**Comment by chloexiangyy** [comment]
Maybe you can see：https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/scripts/visualize_nusc.py

**Comment by youngskkim** [comment]
Thank you @chloexiangyy, you can modify that script to visualize samples.
I also utilized that script and nuscenes official visualization script.
