### ISSUE TITLE
How to split the dataset into Sunny/Rainy/Day/Night scene?

### ISSUE THREAD

**Issue by zx-repo** [youngskkim/CRN#31]
I  would like to konw how to analysis of different lighting and weather conditions in your work. Thanks a lot!

**Comment by lochenchou** [comment]
For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.

**Comment by zx-repo** [comment]
I have done with this step, where should I do scene filtering next in this code

> For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.

Thank you, I have completed this step to get the name of the night scene. What should I do to filter the scene next in this repo?

**Comment by zx-repo** [comment]
> For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.

The problem has been solved, Thank you very much!

**Comment by L1bertad** [comment]
> > For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.
> 
> The problem has been solved, Thank you very much!

Hello! Have you achieved this? Can you tell me how to do it? Thank you very much!

**Comment by zx-repo** [comment]
> > > For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.
> > 
> > 
> > The problem has been solved, Thank you very much!
> 
> Hello! Have you achieved this? Can you tell me how to do it? Thank you very much!
It can be splited by the description of each scene.
such as night:

`nusc = NuScenes(version='v1.0-trainval', dataroot='./data/nuscenes/', verbose=True)

for my_scene in nusc.scene:
    scene_description = my_scene['description']
    if 'Night' in scene_description:`

**Comment by zx-repo** [comment]
> > > For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.
> > 
> > 
> > The problem has been solved, Thank you very much!
> 
> Hello! Have you achieved this? Can you tell me how to do it? Thank you very much!

It can be splited by the description of each scene, such as night:
`nusc = NuScenes(version='v1.0-trainval', dataroot='./data/nuscenes/', verbose=True)

for my_scene in nusc.scene:
    scene_description = my_scene['description']
    if 'Night' in scene_description:`

**Comment by L1bertad** [comment]
> Thank you very much!

Thank you very much!

**Comment by L1bertad** [comment]
> > > > For nuscenes dataset, you could get the description of every sample from nuscenes api with sample data token and just filter out day/night/rain afterward.
> > > 
> > > 
> > > The problem has been solved, Thank you very much!
> > 
> > 
> > Hello! Have you achieved this? Can you tell me how to do it? Thank you very much!
> 
> It can be splited by the description of each scene, such as night: `nusc = NuScenes(version='v1.0-trainval', dataroot='./data/nuscenes/', verbose=True)
> 
> for my_scene in nusc.scene: scene_description = my_scene['description'] if 'Night' in scene_description:`

Thank you very much!
