### ISSUE TITLE
After completing  epoch 1, the process gets stuck and doesn't proceed further, but the GPU memory is still occupied

### ISSUE THREAD

**Issue by Hellohai61** [youngskkim/CRN#33]
After completing the first epoch, the process gets stuck and doesn't proceed further, I can only stop it by pressing Ctrl+C， and the GPU memory is still occupied.Has anyone encountered this issue?
（I run the code on a single 4090 GPU with minimal modifications, The command I'm using is:python ./exps/det/CRN_r50_256x704_128x128_4key.py --amp_backend native -b 4 --gpus 1
）

![issue](https://github.com/user-attachments/assets/76c45f12-b423-45a3-92e6-d634f375d5bf)

**Comment by lcl124252** [comment]
I have the same problem. How did you solve it? Thank you very much
